# SPDX-License-Identifier: PMPL-1.0
name: Elixir CI
on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: '26'
          elixir-version: '1.15'

      - name: Cache deps
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: deps
          key: deps-${{ hashFiles('mix.lock') }}

      - name: Install deps
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Credo lint
        run: mix credo --strict

      - name: Dialyzer
        run: mix dialyzer
        continue-on-error: true

      - name: Run tests
        run: mix test --cover

      - name: Security check
        run: mix deps.audit || true
