# SPDX-License-Identifier: PMPL-1.0
name: Elixir CI
on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: '26'
          elixir-version: '1.15'

      - name: Cache deps
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
        with:
          path: deps
          key: deps-${{ hashFiles('mix.lock') }}

      - name: Install deps
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Credo lint
        run: mix credo --strict

      - name: Dialyzer
        run: mix dialyzer
        continue-on-error: true

      - name: Run tests
        run: mix test --cover

      - name: Security check
        run: mix deps.audit || true
